name: format_write

on:
  push:
    branches: 
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ HOST_SECRET }}
        username: root
        key: OMG_SECRET
        password: ${{ PASS_SECRET }}
        port: 22
        script: ls -a
        
        
        
        
        
        
        
        
        
